#!/bin/bash
#
# Regenerates internal_forms.tsv: a table of Maxima expressions and the internal
# s-expressions they evaluate to.
#
# These are the fixtures the s-expression reader (PLAN.md step 7) and the
# Maxima->Expr mapping (step 9) are written against, so that both can be tested
# with no Maxima installation present. Recorded rather than hand-written,
# because the point is to pin down what Maxima actually emits.
#
# Usage:  tests/golden/record.sh <path-to-maxima.core> [<path-to-sbcl>]
#
set -euo pipefail

CORE=${1:?usage: record.sh <maxima.core> [sbcl]}
SBCL=${2:-sbcl}
OUT="$(dirname "$0")/internal_forms.tsv"

HELPER='(progn
 (defun maxima::$cppsend (id x)
  (let ((ok (and (consp x) (cdr x)))
        (*print-circle* nil) (*print-pretty* nil) (*print-readably* nil))
   (format t "~&@@G@@~a@@~s@@~%" (if ok "OK" "ERR") (if ok (cadr x) nil)))
  (quote maxima::$done))
 (cl-user::run))'

# One expression per line. Chosen to cover every shape the reader has to handle:
# each numeric tower rung, the operator heads, both function-head spellings, and
# the constructs that exist only to prove the escape hatches are needed.
EXPRESSIONS=(
  '42'
  '-7'
  '30!'
  '1/3 + 2/5'
  '-3/4'
  '1.5'
  '1/3.0'
  '1.0e-10'
  'bfloat(%pi)'
  'x'
  'x + 1'
  '2*x*sin(x)'
  'x^2'
  'x^(1/2)'
  '(x+1)*(x-1)'
  'sin(x)'
  'bessel_j(0, x)'
  'f(x)'
  'f(x, y, z)'
  'undefined_fn(3)'
  '%pi'
  '%e'
  '%i'
  'true'
  'false'
  '"a string"'
  '[a, b, c]'
  '[]'
  'x = 1'
  'x > 1'
  'matrix([1,2],[3,4])'
  "'diff(f(x), x)"
  'integrate(x^2*sin(x), x)'
  'solve(x^2 - 1 = 0, x)'
  'expand((x + 1)^3)'
  'taylor(sin(x), x, 0, 5)'
  'rat(x/(x+1))'
  'integrate(x, 5)'
  '1/0'
)

{
  printf '# Generated by tests/golden/record.sh -- do not edit by hand.\n'
  printf '# <expression>\\t<OK|ERR>\\t<internal s-expression>\n'
} > "$OUT"

{
  printf 'display2d:false$\nnolabels:true$\nerrormsg:false$\n'
  for expression in "${EXPRESSIONS[@]}"; do
    printf 'cppsend(0, errcatch(ratdisrep(%s)))$\n' "$expression"
  done
  printf 'quit();\n'
} | "$SBCL" --core "$CORE" --noinform --end-runtime-options \
      --eval "$HELPER" --end-toplevel-options 2>/dev/null \
  | grep -o '@@G@@[^@]*@@.*@@$' \
  | sed 's/^@@G@@//; s/@@$//; s/@@/\t/' \
  | paste <(printf '%s\n' "${EXPRESSIONS[@]}") - >> "$OUT"

printf 'wrote %s (%d cases)\n' "$OUT" "${#EXPRESSIONS[@]}"
